FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements/mlflow_requirements.txt /mlflow_requirements.txt
RUN pip install --no-cache-dir -r /mlflow_requirements.txt